# For more information on using the buildspec see the following link:
# https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html
#
# Use this file to specify how to handle the CloudFormation Stacks for the application
# NOTE: This file uses the -python.yml extension to signify the build of the Lambda
# function relevant to what's required.
version: 0.2 # The version number of the application
phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      # get pipenv
      - pip install pipenv
      # install development requirements
      - cd $SOURCE_PATH
      - pipenv sync --dev
  
  build:
    commands:
      - aws cloudformation package --template-file project-skeleton.cf-template.yaml --s3-bucket pune-dev-codepipeline --output-template-file outputTemplate.yaml
  
artifacts:
  type: zip
  files:
    - '**/*'
  base-directory: $SOURCE_PATH
