version: 0.2
phases:
  build:
    commands:
      - aws cloudformation package --template-file ./templates/project-skeleton.cf-template.yml --s3-bucket pune-dev-codepipeline --output-template-file outputSamTemplate.yaml
artifacts:
  type: zip
  files:
    - project-skeleton.cf-template.yml
    - outputSamTemplate.yaml
